codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 80%
flags:
  flower_classifier:
    paths:
      - "flower_classifier/**"

ignore:
  - "tests/*"
  - "**/scripts/*"

