name: iris
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - shap
  - joblib
  - jupyter
  - notebook
  - nbconvert
  - ipykernel
  - pytest
  - pip
  - pip:
      - -e .
      - streamlit
